question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "India is the world's largest democracy.", "answer": "True"},
    {"text": "The Taj Mahal is located in Jaipur.", "answer": "False"},
    {"text": "The national animal of India is the Bengal Tiger.", "answer": "True"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The Ganges is the longest river in India.", "answer": "False"},
    {"text": "The total surface area of human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "Rashtrapati Bhavan has over 300 rooms.", "answer": "True"},
    {"text": "In West Virginia, USA, if you hit an animal with your car, you can take it home to eat.", "answer": "True"},
    {"text": "India gained independence in 1950.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "The Lotus Temple in Delhi is made entirely of white marble.", "answer": "True"},
    {"text": "The Sun Temple in Konark is dedicated to Lord Vishnu.", "answer": "False"},
    {"text": "India has the second largest population in the world.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can kill a small dog.", "answer": "True"},
    {"text": "Cows have four stomachs.", "answer": "True"},
    {"text": "India's national flag is called the Tiranga.", "answer": "True"},
    {"text": "Bananas grow on trees.", "answer": "False"},
    {"text": "Humans share about 60% of their DNA with bananas.", "answer": "True"},
    {"text": "The India Gate in Delhi was built to commemorate soldiers who died in World War I.", "answer": "True"},
    {"text": "The Indian currency symbol was introduced in 1947.", "answer": "False"},
    {"text": "The peacock is the national bird of India.", "answer": "True"},
    {"text": "India's Kumbh Mela is the largest religious gathering in the world.", "answer": "True"},
    {"text": "Sharks are mammals.", "answer": "False"},
    {"text": "The Gateway of India is located in Mumbai.", "answer": "True"},
    {"text": "Humans have 46 chromosomes.", "answer": "True"},
    {"text": "A group of flamingos is called a flamboyance.", "answer": "True"},
    {"text": "Chennai was formerly known as Madras.", "answer": "True"},
    {"text": "India's space agency is called NASA.", "answer": "False"},
    {"text": "The capital of Rajasthan is Jaipur.", "answer": "True"},
    {"text": "Lightning never strikes the same place twice.", "answer": "False"},
    {"text": "India has 29 states and 8 Union Territories.", "answer": "True"},
    {"text": "The Earth revolves around the Sun in exactly 365 days.", "answer": "False"},
    {"text": "Mahatma Gandhi was assassinated in 1948.", "answer": "True"},
    {"text": "Penguins can fly.", "answer": "False"},
    {"text": "Mount Everest is located in India.", "answer": "False"},
    {"text": "The human heart beats around 100,000 times a day.", "answer": "True"},
    {"text": "Butterflies taste with their feet.", "answer": "True"},
    {"text": "Antarctica is the coldest place on Earth.", "answer": "True"},
    {"text": "Rabindranath Tagore wrote the Indian national anthem.", "answer": "True"},
    {"text": "The Konark Sun Temple is in Gujarat.", "answer": "False"},
    {"text": "The largest state in India by area is Rajasthan.", "answer": "True"},
    {"text": "India's first Prime Minister was Sardar Vallabhbhai Patel.", "answer": "False"},
    {"text": "India hosted the Cricket World Cup in 1983.", "answer": "False"},
    {"text": "The Golden Temple is located in Amritsar.", "answer": "True"},
    {"text": "Saturn is the only planet with rings.", "answer": "False"},
    {"text": "The largest mammal in the world is the blue whale.", "answer": "True"},
    {"text": "India is known as the 'Land of Spices'.", "answer": "True"},
    {"text": "The Brahmaputra River flows through Arunachal Pradesh.", "answer": "True"},
    {"text": "The Red Fort was built during the Mughal period.", "answer": "True"},
    {"text": "The human body contains enough iron to make a small nail.", "answer": "True"},
    {"text": "Snakes are mammals.", "answer": "False"},
    {"text": "The fastest train in India is the Vande Bharat Express.", "answer": "True"},
    {"text": "The Taj Mahal was built by Akbar.", "answer": "False"},
    {"text": "India is the largest producer of tea in the world.", "answer": "False"},
    {"text": "The Indian national calendar is based on the Saka Era.", "answer": "True"},
    {"text": "The Himalayas are the youngest mountain range in the world.", "answer": "True"},
    {"text": "The capital of India is Mumbai.", "answer": "False"},
    {"text": "India's currency is called the Rupee.", "answer": "True"},
    {"text": "The Mangalyaan mission was launched by ISRO.", "answer": "True"},
    {"text": "Kerala is known as 'God's Own Country'.", "answer": "True"},
    {"text": "The first satellite launched by India was Chandrayaan-1.", "answer": "False"},
    {"text": "India has won the FIFA World Cup.", "answer": "False"},
    {"text": "The Andaman and Nicobar Islands are in the Arabian Sea.", "answer": "False"},
    {"text": "Diwali is known as the Festival of Lights.", "answer": "True"},
    {"text": "The Indian Railways is the largest employer in the world.", "answer": "False"},
    {"text": "India's national tree is the Neem tree.", "answer": "False"},
    {"text": "The Corbett National Park was the first national park in India.", "answer": "True"},
    {"text": "Rajasthan is the smallest state in India by area.", "answer": "False"},
    {"text": "The Indian Ocean is the third largest ocean in the world.", "answer": "True"},
    {"text": "India's national fruit is the mango.", "answer": "True"},
    {"text": "India is home to the world’s largest sundial.", "answer": "True"},
    {"text": "The Ajanta caves are in Madhya Pradesh.", "answer": "False"},
    {"text": "Goa was a Portuguese colony.", "answer": "True"},
    {"text": "The Holi festival marks the beginning of spring in India.", "answer": "True"},
    {"text": "India's first President was Dr. Rajendra Prasad.", "answer": "True"},
    {"text": "The Kaveri River flows into the Arabian Sea.", "answer": "False"},
    {"text": "The Indian state with the highest literacy rate is Kerala.", "answer": "True"},
    {"text": "India's Independence Day is celebrated on 15th August.", "answer": "True"},
    {"text": "The national emblem of India features lions.", "answer": "True"}
]
